/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaquotes;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test
    public void testAppHasQuoteReader() {
        App classUnderTest = new App();
        assertNotNull("app should print", classUnderTest);
    }
}
